# Generated by Django 5.2.3 on 2026-02-15 08:08

import uuid

from django.db import migrations, models
from django.db.models import Count


def _generate_unique_phone(existing_values):
    while True:
        candidate = "dup" + uuid.uuid4().hex[:17]
        if candidate not in existing_values:
            return candidate


def fix_duplicate_phone_numbers(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    existing_values = set(
        User.objects.values_list("phone_number", flat=True)
    )

    duplicates = (
        User.objects.values("phone_number")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )

    for entry in duplicates:
        phone_number = entry["phone_number"]
        users = User.objects.filter(phone_number=phone_number).order_by("id")
        for user in users[1:]:
            new_phone = _generate_unique_phone(existing_values)
            user.phone_number = new_phone
            user.save(update_fields=["phone_number"])
            existing_values.add(new_phone)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_notification"),
    ]

    operations = [
        migrations.RunPython(
            fix_duplicate_phone_numbers,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
