# Generated by Django 5.2.3 on 2026-03-02 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chest", models.FloatField()),
                ("shoulder", models.FloatField()),
                ("waist", models.FloatField()),
                ("hips", models.FloatField()),
                ("arm_length", models.FloatField()),
                ("height", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="SuitType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("lapel_count", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the order",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_code", models.CharField(max_length=12, unique=True)),
                (
                    "expected_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("AWAITING_PAYMENT", "Awaiting_approval"),
                            ("PENDING_APPROVAL", "pending_approval"),
                            ("IN_PROGRESS", "In_progress"),
                            ("COMPLETED", "Completed"),
                            ("CLOSED", "Closed"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                            ("FULLY_PAID", "Fully_paid"),
                        ],
                        default="INITIATED",
                        max_length=20,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("due_date", models.DateField()),
                ("payment_reference", models.CharField(blank=True, max_length=120)),
                (
                    "payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("payment_received_at", models.DateTimeField(blank=True, null=True)),
                ("payment_notes", models.TextField(blank=True)),
                ("payment_allowed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="orders.customer",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="inventory.material",
                    ),
                ),
                (
                    "measurement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order",
                        to="orders.measurement",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "suit_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="orders.suittype",
                    ),
                ),
            ],
        ),
    ]
