# Generated by Django 5.2.3 on 2026-03-02 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="color",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chosen_color",
                to="inventory.color",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIATED", "Initiated"),
                    ("AWAITING_PAYMENT", "Awaiting_approval"),
                    ("PENDING_APPROVAL", "pending_approval"),
                    ("IN_PROGRESS", "In_progress"),
                    ("SHIPPED", "Shipped"),
                    ("COMPLETED", "Completed"),
                    ("IN_STORE", "In_store"),
                    ("CLOSED", "Closed"),
                    ("REJECTED", "Rejected"),
                    ("EXPIRED", "Expired"),
                    ("FULLY_PAID", "Fully_paid"),
                ],
                default="INITIATED",
                max_length=20,
            ),
        ),
    ]
