# Generated by Django 5.2.3 on 2026-03-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_color_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIATED", "Initiated"),
                    ("AWAITING_PAYMENT", "Awaiting_approval"),
                    ("PENDING_APPROVAL", "pending_approval"),
                    ("IN_PROGRESS", "In_progress"),
                    ("SHIPPED", "Shipped"),
                    ("COMPLETED", "Completed"),
                    ("IN_STORE", "In_store"),
                    ("CLOSED", "Closed"),
                    ("IN_STORE", "In_store"),
                    ("REJECTED", "Rejected"),
                    ("EXPIRED", "Expired"),
                ],
                default="INITIATED",
                max_length=20,
            ),
        ),
    ]
