# Generated by Django 5.2.4 on 2026-02-12 00:00

from django.db import migrations, models
import django.db.models.deletion


def forwards_copy_measurements(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Measurement = apps.get_model("orders", "Measurement")

    for measurement in Measurement.objects.exclude(order_id=None):
        Order.objects.filter(id=measurement.order_id).update(
            measurement_id=measurement.id
        )


def backwards_copy_measurements(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    Measurement = apps.get_model("orders", "Measurement")

    for order in Order.objects.exclude(measurement_id=None):
        Measurement.objects.filter(id=order.measurement_id).update(order_id=order.id)


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_processing_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="measurement",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="orders.measurement",
            ),
        ),
        migrations.RunPython(forwards_copy_measurements, backwards_copy_measurements),
        migrations.RemoveField(
            model_name="measurement",
            name="order",
        ),
    ]
