# Generated by Django 5.2.4 on 2026-02-12 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_owns_measurement"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
