# Generated by Django 5.2.3 on 2026-03-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="color",
            new_name="selected_color",
        ),
    ]
