# Generated by Django 5.2.4 on 2026-02-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_reviewed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
