# Generated by Django 5.2.4 on 2026-02-12 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_id"),
        ("orders", "0005_order_payment_allowed"),
    ]

    operations = []
