# Generated by Django 5.2.4 on 2026-02-12 00:00

import uuid
from django.db import migrations, models


def populate_order_code(apps, schema_editor):
    Order = apps.get_model("orders", "Order")

    for order in Order.objects.filter(order_code__isnull=True):
        code = uuid.uuid4().hex[:10].upper()
        while Order.objects.filter(order_code=code).exists():
            code = uuid.uuid4().hex[:10].upper()
        order.order_code = code
        order.save(update_fields=["order_code"])


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_payment_allowed"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_code",
            field=models.CharField(max_length=12, unique=True, null=True),
        ),
        migrations.RunPython(populate_order_code, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="order",
            name="order_code",
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
