# Generated by Django 5.2.4 on 2026-02-12 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_merge_0002_alter_order_id_0005_order_payment_allowed"),
        ("orders", "0006_order_order_code"),
    ]

    operations = []
