# Generated by Django 5.2.3 on 2026-02-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_merge_20260212_1931"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="expected_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="full_price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIATED", "Initiated"),
                    ("AWAITING_PAYMENT", "Awaiting_approval"),
                    ("PENDING_APPROVAL", "pending_approval"),
                    ("IN_PROGRESS", "In_progress"),
                    ("COMPLETED", "Completed"),
                    ("CLOSED", "Closed"),
                    ("REJECTED", "Rejected"),
                    ("EXPIRED", "Expired"),
                    ("FULLY_PAID", "Fully_paid"),
                ],
                default="INITIATED",
                max_length=20,
            ),
        ),
    ]
