# Generated by Django 5.2.3 on 2026-02-10 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=100)),
                ("texture", models.CharField(blank=True, max_length=100, null=True)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_meters",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "material",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory",
                        to="inventory.material",
                    ),
                ),
            ],
        ),
    ]
