# Generated by Django 5.2.3 on 2026-03-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="material_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/materials/clothes/"
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="suit_sample_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/materials/suits/"
            ),
        ),
    ]
