# Generated by Django 5.2.3 on 2026-02-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="category",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
