# Generated by Django 5.2.4 on 2026-02-12 00:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="customer_full_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="transaction",
            name="customer_phone_number",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
    ]
