# Generated by Django 5.2.3 on 2026-02-14 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_transaction_payment_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="customer_full_name",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="customer_phone_number",
        ),
    ]
