# Generated by Django 5.2.3 on 2026-02-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_remove_transaction_customer_full_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="receipt_screenshot",
            field=models.FileField(
                blank=True, null=True, upload_to="receipts/screenshots/"
            ),
        ),
    ]
