# Generated by Django 5.2.3 on 2026-02-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_remove_transaction_customer_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="bank_ref_number",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
