# Generated by Django 5.2.3 on 2026-02-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_add_receipt_screenshot"),
    ]

    operations = []
