# Generated by Django 5.1.6 on 2026-02-21 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_transaction_bank_ref_number'),
        ('payments', '0004_transaction_receipt_screenshot'),
    ]

    operations = [
    ]
